export const metroSeed = {
  _id: 'metro-data',
  metroLines: {
    PURPLE: {
      name: 'Purple Line',
      color: '#7B2FBE',
      stations: [
        'Whitefield (Kadugodi)', 'Kadugodi Tree Park', 'Pattandur Agrahara',
        'Sri Sathya Sai Hospital', 'Nallurhalli', 'Seetharam Palya', 'Hoodi',
        'Garudacharpalya', 'KR Pura', 'Benniganahalli', 'Baiyappanahalli',
        'Swami Vivekananda Road', 'Indiranagar', 'Halasuru', 'Trinity',
        'MG Road', 'Cubbon Park', 'Vidhana Soudha', 'Central College',
        'Majestic', 'City Railway Station', 'Magadi Road', 'Hosahalli',
        'Vijayanagar', 'Attiguppe', 'Deepanjali Nagar', 'Mysuru Road',
        'Rajarajeshwari Nagar', 'Nayandahalli', 'Jnanabharathi',
        'Pattanagere', 'Kengeri', 'Kengeri Bus Terminal', 'Challaghatta',
      ],
    },
    GREEN: {
      name: 'Green Line',
      color: '#149447',
      stations: [
        'Madavara', 'Chikkabidarakallu', 'Manjunathanagar', 'Dasarahalli',
        'Jalahalli', 'Peenya Industry', 'Peenya', 'Goraguntepalya',
        'Yeshwantpur', 'Sandal Soap Factory', 'Mahalakshmi', 'Rajajinagar',
        'Kuvempu Road', 'Srirampura', 'Sampige Road', 'Majestic',
        'Chickpete', 'KR Market', 'National College', 'Lalbagh',
        'South End Circle', 'Jayanagar', 'RV Road', 'Banashankari',
        'Jayaprakash Nagar', 'Yelachenahalli', 'Konanakunte Cross',
        'Doddakallasandra', 'Vajarahalli', 'Thalaghattapura', 'Silk Institute',
      ],
    },
    YELLOW: {
      name: 'Yellow Line',
      color: '#D99A00',
      stations: [
        'RV Road', 'Ragigudda', 'Jayadeva Hospital', 'BTM Layout',
        'Silk Board', 'Bommanahalli', 'Hongasandra', 'Kudlu Gate',
        'Singasandra', 'Hosa Road', 'Beratena Agrahara',
        'Electronic City', 'Konnapana Agrahara', 'Huskur Road',
        'Hebbagodi', 'Bommasandra',
      ],
    },
    PINK: {
      name: 'Pink Line',
      color: '#D62976',
      stations: [
        'Kalena Agrahara', 'Hulimavu', 'IIM Bangalore', 'JP Nagar 4th Phase',
        'Jayadeva Hospital', 'Tavarekere', 'Dairy Circle', 'Lakkasandra',
        'Langford Town', 'Rashtriya Military School', 'MG Road',
        'Shivajinagar', 'Cantonment', 'Pottery Town', 'Tannery Road',
        'Venkateshpura', 'Kadugundanahalli', 'Nagawara',
      ],
    },
    BLUE: {
      name: 'Blue Line',
      color: '#1266B0',
      stations: [
        'Silk Board', 'HSR Layout', 'Agara Lake', 'Iblur', 'Bellandur',
        'Kadubeesanahalli', 'Devarabeesanahalli', 'Marathahalli',
        'ISRO (Karthik Nagar)', 'Doddanekundi', 'DRDO Sports Complex',
        'Mahadevapura', 'KR Pura', 'Horamavu', 'HRBR Layout',
        'Kalyan Nagar', 'HBR Layout', 'Nagawara', 'Veerannapalya',
        'Kempapura', 'Hebbal', 'Kodigehalli', 'Jakkur Cross',
        'Yelahanka', 'Bagalur Cross', 'Bettahalasuru', 'Doddajala',
        'Airport City', 'Kempegowda International Airport',
      ],
    },
  },
  interchanges: ['Majestic', 'KR Pura', 'RV Road', 'Jayadeva Hospital', 'MG Road', 'Nagawara', 'Silk Board'],
  fareRules: {
    slabs: [
      { maxStations: 2, fare: 10 },
      { maxStations: 4, fare: 20 },
      { maxStations: 6, fare: 30 },
      { maxStations: 8, fare: 40 },
      { maxStations: 10, fare: 50 },
      { maxStations: 15, fare: 60 },
      { maxStations: 20, fare: 70 },
      { maxStations: 25, fare: 80 },
      { maxStations: null, fare: 90 },
    ],
    discounts: {
      cardPeak: 0.05,
      cardNonPeak: 0.10,
      cardHoliday: 0.10,
    },
  },
  timings: [
    {
      line: 'Purple Line',
      color: '#7B2FBE',
      terminal: 'Whitefield (Kadugodi) <-> Challaghatta',
      firstTrain: '05:00 AM',
      lastTrain: '11:35 PM',
      sundayFirst: '07:00 AM',
      sundayLast: '11:00 PM',
      peakFrequency: '3-5 min',
      offPeakFrequency: '8-10 min',
      peakHours: '08:00-11:00 AM / 05:00-07:30 PM',
      notes: 'Last train departs Mysuru Road at 11:35 PM; Baiyappanahalli at 11:40 PM.',
    },
    {
      line: 'Green Line',
      color: '#149447',
      terminal: 'Madavara <-> Silk Institute',
      firstTrain: '05:00 AM',
      lastTrain: '11:25 PM',
      sundayFirst: '07:00 AM',
      sundayLast: '11:00 PM',
      peakFrequency: '3-5 min',
      offPeakFrequency: '8-10 min',
      peakHours: '08:00-11:00 AM / 05:00-07:30 PM',
      notes: 'First train from Nagasandra to Yelachenahalli at 05:00 AM. Last at 11:25 PM.',
    },
    {
      line: 'Yellow Line',
      color: '#D99A00',
      terminal: 'RV Road <-> Bommasandra',
      firstTrain: '06:00 AM',
      lastTrain: '10:00 PM',
      sundayFirst: '08:00 AM',
      sundayLast: '10:00 PM',
      peakFrequency: '8-10 min',
      offPeakFrequency: '12-15 min',
      peakHours: '08:00-11:00 AM / 05:00-07:30 PM',
      notes: 'Partial operations underway. Frequency improving as ridership grows.',
    },
    {
      line: 'Pink Line',
      color: '#D62976',
      terminal: 'Kalena Agrahara <-> Nagawara',
      firstTrain: 'TBD',
      lastTrain: 'TBD',
      sundayFirst: 'TBD',
      sundayLast: 'TBD',
      peakFrequency: 'TBD',
      offPeakFrequency: 'TBD',
      peakHours: '-',
      notes: 'Under construction. Launch details will be updated when service opens.',
    },
    {
      line: 'Blue Line',
      color: '#1266B0',
      terminal: 'Silk Board <-> Kempegowda International Airport',
      firstTrain: 'TBD',
      lastTrain: 'TBD',
      sundayFirst: 'TBD',
      sundayLast: 'TBD',
      peakFrequency: 'TBD',
      offPeakFrequency: 'TBD',
      peakHours: '-',
      notes: 'Part of Phase 2 expansion. ORR corridor is under construction.',
    },
    {
      line: 'General Service Rules',
      color: '#475569',
      terminal: 'All Lines',
      firstTrain: '05:00 AM',
      lastTrain: '11:35 PM',
      sundayFirst: '07:00 AM',
      sundayLast: '11:00 PM',
      peakFrequency: '3-5 min',
      offPeakFrequency: '8-15 min',
      peakHours: '08:00-11:00 AM / 05:00-07:30 PM',
      notes: 'Services may be extended during major festivals/events. Timings are subject to change.',
    },
  ],
};
